### ISSUE TITLE
No matching export in "browser-external:fs" for import "existsSync"

### ISSUE THREAD

**Issue by softboy99** [antfu/local-pkg#3] opened 2022-06-17 06:21 UTC
No matching export in "browser-external:fs" for import "existsSync"

**Comment by antfu** [comment] 2022-06-17 06:58
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2022-06-17 06:58 UTC
